config/routes.rb
Rails.application.routes.draw do
  resources :trojan_virus_malwares
  get 'trojan_hack/new'
  get 'trojan_hack/create'
  devise_for :users
  resources :pins
  get 'home/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pins#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/pin.rb
class Pin < ApplicationRecord
    has_one_attached :image
    has_many_attached :pictures
    has_rich_text :body

    def image_as_thumbnail
        image.variant(resize_to_limit: [300, 300].processed)
    end
    
end

app/models/trojan_hack.rb
class TrojanHack < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pins_controller.rb
class PinsController < InheritedResources::Base
  

  private

    def pin_params
      params.require(:pin).permit(:title, :body, :image, pictures: [])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/trojan_hack_helper.rb
module TrojanHackHelper
end

app/helpers/user_viri_helper.rb
module UserViriHelper
end

app/helpers/user_virus_helper.rb
module UserVirusHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/home/_header.html.erb
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">All in one rails application</li>
      <li>
        <a href="#">Features</a>
        <ul class="menu vertical">
          <li><a href="<%= 'home/index' %>">Datatables</a></li>
          <li><a href="<%= 'pins' %>">Posting - BLog etc.</a></li>
          <li><a href="<%= 'trojan_virus_malwares' %>">A Virus which sends Mail</a></li>
        </ul>
      </li>
      <% if user_signed_in? %>
        <%= link_to "LogOut", destroy_user_session_path, method: :delete, data: {turbo_method: :delete}, class:"nav-link" %>
        <li><a href="<%= edit_user_registration_path %>">Profile</a></li>
      <% else %>
      <li><a href="<%= new_user_session_path %>">Login</a></li>
      <li><a href="<%= new_user_registration_path %>">Sign Up</a></li>
      <% end %>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><input type="search" placeholder="Search"></li>
      <li><button type="button" class="button">Search</button></li>
    </ul>
  </div>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>


<div data-controller ="home">

    <p>Welcome to home page</p>

    <button type="button" class="button" data-toggle="offCanvasLeft1">Open Left</button>
    <button type="button" class="button" data-toggle="offCanvasRight1">Open Right</button>
    <button type="button" class="button" data-toggle="offCanvasTop1">Open Top</button>
    <button type="button" class="button" data-toggle="offCanvasBottom1">Open Bottom</button>

    <div class="cell">
        <div class="off-canvas-wrapper">
          <div class="off-canvas position-left" id="offCanvasLeft1" data-off-canvas>
            <!-- Your menu or Off-canvas content goes here -->
          </div>
          <div class="off-canvas position-right" id="offCanvasRight1" data-off-canvas>
            <!-- Your menu or Off-canvas content goes here -->
          </div>
          <div class="off-canvas position-top" id="offCanvasTop1" data-off-canvas>
            <!-- Your menu or Off-canvas content goes here -->
          </div>
          <div class="off-canvas position-bottom" id="offCanvasBottom1" data-off-canvas>
            <!-- Your menu or Off-canvas content goes here -->
          </div>
          <div class="off-canvas-content" data-off-canvas-content>
            <img src="https://placehold.it/300x300" class="" height="" width="" alt="">
          </div>
        </div>
    </div>


    <table id="example" class="display" style="width:100%">
      <thead>
        <tr>
          <th>Lastname</th>
          <th>Firstname</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Messiani</td>
          <td>Cristiano</td>
        </tr>
        <tr>
          <td>Rolando</td>
          <td>Esteban</td>
        </tr>
        <tr>
          <td>Traoré</td>
          <td>Adam</td>
        </tr>
      </tbody>
    </table>

</div>

<script>
  document.addEventListener('DOMContentLoaded', function () {
    let table = new DataTable('#example');
  });
</script>

</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdminTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'home/header'%>
    <%= yield %>
  </body>
</html>

app/views/pins/_form.html.erb
<%= form_with(model: pin) do |form| %>
  <% if pin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
        <% pin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.rich_text_area :body %>
  </div>

  <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.label :pictures %>
    <%= form.file_field :pictures, multiple: true%>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div id="<%= dom_id pin %>">
  <p>
    <strong>Title:</strong>
    <%= pin.title %>
  </p>

  <%= pin.body %>

  <br />

  <%= link_to(pin.image, target: '_blank') do %>
  <%= image_tag(pin.image, style: "width:150px; height:150px") %>
<% end %>
  <br />
  
  <% pin.pictures.each do |picture| %>
  <%= link_to picture, target: '_blank' do %>
    <%= image_tag(picture, style: "width:150px; height:150px") %>
  <% end %>
<% end %>

</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render "form", pin: @pin %>

<br>

<div>
  <%= link_to "Show this pin", @pin %> |
  <%= link_to "Back to pins", pins_path %>
</div>

app/views/pins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pins</h1>

<div id="pins">
  <% @pins.each do |pin| %>
    <%= render pin %>
    <p>
      <%= link_to "Show this pin", pin %>
    </p>
  <% end %>
</div>

<%= link_to "New pin", new_pin_path %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render "form", pin: @pin %>

<br>

<div>
  <%= link_to "Back to pins", pins_path %>
</div>

app/views/pins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pin %>

<div>
  <%= link_to "Edit this pin", edit_pin_path(@pin) %> |
  <%= link_to "Back to pins", pins_path %>

  <%= button_to "Destroy this pin", @pin, method: :delete %>
</div>

app/views/trojan_hack/create.html.erb
<h1>TrojanHack#create</h1>
<p>Find me in app/views/trojan_hack/create.html.erb</p>

app/views/trojan_hack/new.html.erb
<h1>TrojanHack#new</h1>
<p>Find me in app/views/trojan_hack/new.html.erb</p>

app/views/user_viri/_form.html.erb
<%= form_with(model: user_virus) do |form| %>
  <% if user_virus.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_virus.errors.count, "error") %> prohibited this user_virus from being saved:</h2>

      <ul>
        <% user_virus.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_area :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_area :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/user_viri/_user_virus.html.erb
<div id="<%= dom_id user_virus %>">
  <p>
    <strong>Email:</strong>
    <%= user_virus.email %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= user_virus.password %>
  </p>

</div>

app/views/user_viri/edit.html.erb
<h1>Editing user virus</h1>

<%= render "form", user_virus: @user_virus %>

<br>

<div>
  <%= link_to "Show this user virus", @user_virus %> |
  <%= link_to "Back to user viri", user_viri_path %>
</div>

app/views/user_viri/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>User viri</h1>

<div id="user_viri">
  <% @user_viri.each do |user_virus| %>
    <%= render user_virus %>
    <p>
      <%= link_to "Show this user virus", user_virus %>
    </p>
  <% end %>
</div>

<%= link_to "New user virus", new_user_virus_path %>

app/views/user_viri/new.html.erb
<h1>New user virus</h1>

<%= render "form", user_virus: @user_virus %>

<br>

<div>
  <%= link_to "Back to user viri", user_viri_path %>
</div>

app/views/user_viri/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_virus %>

<div>
  <%= link_to "Edit this user virus", edit_user_virus_path(@user_virus) %> |
  <%= link_to "Back to user viri", user_viri_path %>

  <%= button_to "Destroy this user virus", @user_virus, method: :delete %>
</div>